# Generated by Django 3.0.6 on 2020-05-23 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200522_1845'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
