# Generated by Django 3.0.6 on 2020-05-15 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(help_text="You'll use the title to find this Note in the future.", max_length=255)),
                ('content', models.TextField(help_text='Write your Note content here. You can use markdown for better formatting.')),
                ('is_public', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('reference_url', models.URLField()),
                ('reference_desc', models.TextField(blank=True, max_length=255)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='notes.Note')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
