# Generated by Django 3.0.6 on 2020-05-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='body',
        ),
        migrations.AddField(
            model_name='note',
            name='content',
            field=models.TextField(default='', help_text='Write your note content here. You can use markdown for better formatting.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(help_text="You'll use the title to find this note in the future.", max_length=255),
        ),
        migrations.AlterField(
            model_name='reference',
            name='reference_desc',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
