# Generated by Django 3.0.6 on 2020-05-18 14:16

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='document_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='note',
            index=django.contrib.postgres.indexes.GinIndex(fields=['document_vector'], name='notes_note_documen_ee33cd_gin'),
        ),
        migrations.RunSQL(
            '''
            CREATE TRIGGER document_vector_update 
            BEFORE INSERT OR UPDATE
            ON notes_note FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(document_vector, 'pg_catalog.english', title, content);
            ''',
        ),
    ]
