# Generated by Django 3.0.6 on 2020-05-15 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20200515_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='is_private',
        ),
        migrations.AddField(
            model_name='note',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
