# Generated by Django 3.0.6 on 2020-05-19 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_notemetadata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notemetadata',
            old_name='clones',
            new_name='num_clones',
        ),
        migrations.RenameField(
            model_name='notemetadata',
            old_name='views',
            new_name='num_views',
        ),
    ]
