# Generated by Django 3.0.6 on 2020-05-20 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20200519_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='notemetadata',
            name='cloned_note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='notes.Note'),
        ),
    ]
